version: "{build}-{branch}"

after_build: |- 
    # Common script that runs after the build script
    cd build 
    shopt -s extglob  # Enable bash extended globbing
    rm -rf build-archive
    mkdir build-archive
    mv *_artefacts/Release/@(VST3|AU|AAX)/*.@(vst3|component|aax) build-archive/

    REPO_NAME=$(echo $APPVEYOR_REPO_NAME | cut -d'/' -f2)
    TAG=$APPVEYOR_REPO_TAG_NAME
    ARCH=$ARCH

    # Create the zip file
    cd build-archive
    zip -r ../"${REPO_NAME}-${TAG}-${worker_os}-${ARCH}.zip" *

for:
  - matrix: { only: [ appveyor_build_worker_image: &linux Ubuntu1804 ] }
    install: |-
      # set -e

      sudo sed -i '/arch=/! s/^deb/deb [arch=amd64,i386]/' /etc/apt/sources.list

      install-deps() {
        # sudo add-apt-repository --remove "deb http://apt.postgresql.org/pub/repos/apt/ bionic-pgdg main"
        local arch="$1"; shift
        local native=("$@" php-cli qemu-user-binfmt )
        local target=()

        sudo dpkg --add-architecture $arch
        sudo apt-get update -qq
        sudo apt-get install -qq aptitude > /dev/null
        sudo aptitude install -yR ${native[@]} ${target[@]/%/:$arch} > /dev/null
      }
      
      sudo update-alternatives --set gcc /usr/bin/gcc-7
      sudo apt-get install -qq --allow-downgrades libstdc++6=8.4.0-1ubuntu1~18.04 > /dev/null

      sudo apt-get install -y \
        libasound2-dev libjack-jackd2-dev \
        ladspa-sdk \
        libcurl4-openssl-dev  \
        libfreetype6-dev \
        libx11-dev libxcomposite-dev libxcursor-dev libxcursor-dev libxext-dev libxinerama-dev libxrandr-dev libxrender-dev \
        libwebkit2gtk-4.0-dev \
        libglu1-mesa-dev mesa-common-dev

      case $ARCH in
      x86_64)
        install-deps amd64
        ;;
      i686)
        install-deps i386 g++-multilib
        export TOOLCHAIN=$(pwd)/cmake/linux-cross.cmake \
               TOOLCHAIN_PREFIX=i386-linux-gnu
        ;;
      armv7l)
        install-deps armhf g++-arm-linux-gnueabihf
        export TOOLCHAIN=$(pwd)/cmake/linux-cross.cmake \
               TOOLCHAIN_PREFIX=arm-linux-gnueabihf
        ;;
      aarch64)
        install-deps arm64 g++-aarch64-linux-gnu
        export TOOLCHAIN=$(pwd)/cmake/linux-cross.cmake \
               TOOLCHAIN_PREFIX=aarch64-linux-gnu
        ;;
      esac

    build_script: |-
        cmake -B build -DCMAKE_BUILD_TYPE=Release
        cmake --build build

    artifacts:
      - path: build/*.zip

  - matrix: { only: [ appveyor_build_worker_image: macos-mojave ] }
    install:
      - |-
        curl -fsSLO https://github.com/Kitware/CMake/releases/download/v3.22.6/cmake-3.22.6-macos-universal.tar.gz
        tar xf cmake-3.22.6-macos-universal.tar.gz
        export PATH=$(pwd)/cmake-3.22.6-macos-universal/CMake.app/Contents/bin:$PATH

        export HOMEBREW_NO_AUTO_UPDATE=1

        brew install gnu-sed

        DEPLOY_TARGET=10.9
        # export SDKROOT=/Library/Developer/CommandLineTools/SDKs/MacOSX10.13.sdk
        # curl -fsSLO https://github.com/phracker/MacOSX-SDKs/releases/download/10.15/MacOSX10.13.sdk.tar.xz
        # # echo 608a89db8b4be150a945871230b5ba5d4767a8500bc5fe76ddf10f5cec5ef513 MacOSX10.13.sdk.tar.xz | sha256sum -c
        # sudo tar xf MacOSX10.13.sdk.tar.xz -C /Library/Developer/CommandLineTools/SDKs
        # sudo xcode-select -s /Library/Developer/CommandLineTools


        sudo xcode-select -s /Applications/Xcode-9.4.1.app

      - |-
        sudo curl -k https://curl.se/ca/cacert.pem -o /etc/ssl/cert.pem

    build_script: |-
        cmake -B build -DCMAKE_BUILD_TYPE=Release -DMAC_OS_X_VERSION_10_14=1 \
        -DCMAKE_OSX_ARCHITECTURES=$ARCH -DCMAKE_OSX_DEPLOYMENT_TARGET=$DEPLOY_TARGET

        cmake --build build -DMAC_OS_X_VERSION_10_14=1

    artifacts:
      - path: build/*.zip

environment:
  BUILD_NUMBER: $(APPVEYOR_BUILD_NUMBER)
  REPO_COMMIT: $(APPVEYOR_REPO_COMMIT)
  REPO_TAG: $(APPVEYOR_REPO_TAG_NAME)

  matrix:
    - job_name: macOS x86 32-bit
      appveyor_build_worker_image: macos-mojave
      worker_os: MacOSX
      ARCH: i386
    - job_name: Linux ARM 32-bit
      appveyor_build_worker_image: *linux
      worker_os: Linux
      ARCH: armv7l
    - job_name: Linux x86 32-bit
      appveyor_build_worker_image: *linux
      worker_os: Linux
      ARCH: i686
    - job_name: Linux ARM 64-bit
      appveyor_build_worker_image: *linux
      worker_os: Linux
      ARCH: aarch64

deploy:
  provider: GitHub
  draft: true
  description: ''
  force_update: true
  auth_token:
    secure: Rk8do2Q/etdabjwIABBRdTJu1a4wYVu9Ltz8HJuC0wc3rz+hHUMGa3N7vTlsrd7z
  artifact: /.*\.(.zip|dll|dylib|so|lua|exe|pkg|pdb)/
  on:
    APPVEYOR_REPO_TAG: true